### ISSUE TITLE
GBX/GBP Issue with quotes updates

### ISSUE THREAD

**Issue by RahulOza** [36bits/msmquote#14]
Quotes not updating in the right denomiation.

GBP are being updated as GBX

e.g. FTSE Developed World UCITS ETF shows £0.66 rather than £66

Caused a lot of rework with a number of funds, am I doing something wrong?

**Comment by 36bits** [comment]
Please let me know the following from the investment details page in Money for this ETF:

1. The symbol you are using;
2. What _Country/Region_ is set to.

**Comment by RahulOza** [comment]
1. VUSA
2. Set to Great Britain

**Comment by RahulOza** [comment]
Also the one above FTSE Developed World UCITS ETF symbol is VEVE, country set to Great Britain

**Comment by 36bits** [comment]
OK I can see the issue here. Yahoo Finance provides some sterling-denominated quotes in GB pounds with symbol `GBP` and others in GP pence with symbol `GBp`, however msmquote currently treats both of these as GB pence quotes. VUSA and VEVE are both quoted with `GBP` which msmquote erroneously takes as a `GBp` value, hence the issue. This is easily resolved with an update to msmquote - I'll release a new version in the next couple of days.
