### ISSUE TITLE
Index Funds Not Updating

### ISSUE THREAD

**Issue by steve1515** [36bits/msmquote#15]
I have these index funds in my "Investments to Watch" section. They don't seem to be getting updated even though my other stocks and funds do.
![image](https://github.com/36bits/msmquote/assets/42748480/7fd93b11-3fb8-42e7-a3df-5be90f19acdf)

**Comment by 36bits** [comment]
Hi, first thing to check is that these securities are set to update - see instructions [here](https://github.com/36bits/msmquote/wiki/How-To#select-which-securities-to-update).

**Comment by steve1515** [comment]
Just confirmed. They were checked in the list.

**Comment by 36bits** [comment]
OK, can you send the log output from the msmquote run to me: jonathan@pueblo.co.uk.

**Comment by steve1515** [comment]
Done! You should have it now.

**Comment by 36bits** [comment]
Thanks. I can see the likely cause of this - please could you also confirm the base currency for your Money file?

**Comment by steve1515** [comment]
If this is the correct place to check, then I have it set to US dollar.
![image](https://github.com/36bits/msmquote/assets/42748480/77cb1fa6-3d49-4747-8029-5828e3b771c3)

**Comment by 36bits** [comment]
Thanks. The issue here is that currently msmquote automatically translates the symbols COMPX, INDU and INX to their Yahoo equivalents when these symbols are prefixed with `$US:` in the Money file, which is the case when the base currency is something other than USD. It's a relatively easy change to the code to enable this translation when the Money base currency is USD and the prefix is jut `$` as is your case - I'll incorporate this into the next release.

In the meantime you can work around the issue by manually changing the symbols in your Money file: 
$COMPX to ^IXIC
$INDU to ^DJI
$INX to ^GSPC

**Comment by Pinkyloo** [comment]
In the Symbol Column in the Money2005 FR  for ^GSPC, I must have US:^GSPC otherwise the indice is quoted in EUR
