### ISSUE TITLE
MSMQuote prevents price update using QIF or manually

### ISSUE THREAD

**Issue by joedempsey52** [36bits/msmquote#16]
I have noticed that the version of MSMQuote I use to update my Microsoft Money file with stock prices from a Google spreadsheet prevents me importing account statement using a qif file

It also seems to block manual updates to prices

A Quick Repair unblocks the problem - but this is a bit annoying

**Comment by 36bits** [comment]
Could you confirm the type of account for which the QIF import fails?

**Comment by agnivesh** [comment]
The issue also occurs if Yahoo Finance is used as a source. Once the mny file has been updated, trying to enter prices manually doesn't work. Quick repair seems to fix the issue.  
 
Let me know if you need any more details.

Version: msmquote-4.2.0

**Comment by joedempsey52** [comment]
Sorry, I missed the e-mail re your message

I import the transactions into an investment account.
The account has a cash account associated with it
There are 3 transactions in a set - one is a sell transaction, the other two are interest received and Other expenses - all for the one investment.
If I delete the sell transaction from the qif file, the other two import without any problem.
The sell transaction on its own is refused - but I have no idea why

**Comment by joedempsey52** [comment]
As for the same problem using Yahoo as a source, I would certainly expect the same problem. I don't think the problem is because of the source data but rather that MSMQUOTES updates the Money files incorrectly

**Comment by 36bits** [comment]
Thanks for that.

This issue occurs after msmquote has added new rows to the Money security price table, ie. when quote data has been received for a date that wasn't previously in the table.

Then, when a manual price update or an investment buy or sell transaction is entered in Money, also for a new date that is not yet in the security price table, the update/transaction is unsuccessful. No other Money operations appear to be affected. For the moment the workaround is to run a _Quick File Repair_ when this situation is encountered.

The root cause is almost certainly an issue with the way jackcess, the third-party library used by msmquote, adds rows to the Money database.

**Comment by 36bits** [comment]
I'm currently testing an update to msmquote that fixes this issue. The root cause didn't lie with jackcess but with an internal Money database value that needed to be updated after the addition of new rows to the security price table (or, in fact, the addition of new rows to any table).

If the testing proves successful then I'll incorporate the fix into the next release.
